# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.
name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Set up JDK 26 (Vector API Core)
        uses: actions/setup-java@v4
        with:
          java-version: '26'
          distribution: 'oracle'
          
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      - name: Build Apex Engine
        run: ./gradlew build --stacktrace
